---
title: "2019 Monsanto Volatility SB22 audps"
author: "SS"
date: "12/2/2019"
output: html_document
---

```{r include=FALSE}
library(betareg)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(lme4)
library(car)
library(emmeans)
library(multcompView)
library(agricolae)
library(nlme)
library(lmerTest)
library(multcomp)
library(bestNormalize)
library(glmmTMB)
library(ggpubr)
library(nortest)
library(zoo)
library(predictmeans)
library(RColorBrewer)
library(CircStats)
library(openair)
library(scales)
library(grDevices)
```

```{r echo=TRUE}
Data <- read.csv("2019 SB22 Hoophouse_Data.csv", header=T)
str(Data)
Data$Distance= as.numeric(Data$Distance)
Data$Trt= as.factor(Data$Trt)
str(Data)
```

```{r Raw injury figure, echo=FALSE}
data1 = Data %>%
  filter(DAT=="28")
data1 <- subset(data1, Trt!="8")
table(data1$Trt)
table(droplevels(data1)$Trt)
str(data1)

names = c("Xtendimax + RUP PMAX + MON 51817 + Intact", "RupXtend II Complete", "RupXtend II Complete + Liberty", 
          "RupXtend II Vgrip", "RupXtend II Vgrip + MON 51817","RupXtend II Vgrip + Liberty",
          "RupXtend II Vgrip + Liberty + MON 51817 + Intact")
names(names) = c("1", "2", "3", "4", "5", "6", "7")

ggplot(data1, aes(x = Distance, y=Injury, group=Distance, fill=Injury)) +
  geom_jitter(alpha=0.2, color="slateblue3") + geom_boxplot(fill="lightsteelblue4") +
  facet_wrap(~Trt, labeller = labeller(Trt=names)) + 
  ggtitle("2019 Bayer Low Tunnel") +
  theme_bw() + theme(plot.title =  element_text(size=18, color="black", face="bold"),
                     axis.title.y = element_text(size=15, color="black", face="bold"),
                     axis.title.x = element_text(size=12, color="black"), 
                     legend.position="none",
                     axis.text.x = element_text(size=6, color="black"),
                     axis.text.y = element_text(size=10, color="black"), 
                     strip.text.x = element_text(size=7, color="black"),
                     panel.background = element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="Injury (%)", x="Distance from Plot Center (m)") +
  scale_x_continuous(breaks=c(0,0.3,0.6,0.9,1.2,1.5,1.8,2.1,2.4,2.7, 3)) +
  ggsave("2019 Raw injury.tiff", units="in", width=10, height=8, dpi=600)
```

AUDPS analysis
```{r AUDPS/AUIDS calculations, echo=TRUE}
#changed trt and rep and re-filtered "data" and calculated audps using function below
data = Data %>%
  filter(DAT=="28", Rep=="3", Trt=="7")
plot(data$Distance, data$Injury)
audps(data$Injury, data$Distance, type="absolute")
```

```{r Data import/raw means, echo=TRUE}
Data2 <- read.csv("2019 SB22 Hoophouse_Data AUDPS.csv", header=T)
str(Data2)
Data2$Trt= as.factor(Data2$Trt)
Data2$Rep=as.factor(Data2$Rep)
str(Data2)

mean <-round(tapply(Data2$AUDPS,Data2$Trtdes, mean),2)
mean
```

```{r Model assumptions, warning=FALSE}
Data2 <- subset(Data2, Trtdes!="Untreated")
table(Data2$Trtdes)
table(droplevels(Data2)$Trtdes)
str(Data2)

ggdensity(Data2$AUDPS, Main = "Density Plot", xlab = "AUDPS")
ggqqplot(Data2$AUDPS)
pearson.test(Data2$AUDPS)
leveneTest(AUDPS ~ Trtdes, data=Data2)

#model using nontransformed data as passed tests above
model=lmer(AUDPS ~ Trtdes + (1|Rep), data=Data2)
summary(model)
anova(model, test.statistic = "F")

lsm <- emmeans(model, ~ Trtdes, adjust="none", contr="pairwise")
lsm

cld <- CLD(lsm, adjust="none", reversed=TRUE, Letters= letters)
cld
```

```{r AUDPS figure, echo=FALSE}
ggplot(cld, aes(x = Trtdes, y=emmean, label=.group, fill=emmean)) +
  #geom_boxplot(fill="plum4") +
  geom_errorbar(aes(ymin  =  lower.CL, ymax  =  upper.CL), width =  0.3, size  =  1, color="slategray4") +
  ggtitle("2019 Bayer Low Tunnel") +
  theme_bw() + theme(plot.title =  element_text(size=18, color="black", face="bold"),
                     axis.title.y = element_text(size=15, color="black", face="bold"),
                     legend.position="none",
                     axis.text.x = element_text(size=10, angle=45, hjust=1, color="black"),
                     axis.text.y = element_text(size=10, color="black"), 
                     #strip.text.x = element_text(size=8, color="black"),
                     panel.background = element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  labs(y="AUDPS", x="") +
  geom_text(size = 3,
            #nudge_x = c(1, 1, 1, 1, 1, 1, 1),
            nudge_y = c(30, 30, 30, 30, 30, 30, 30),
            color   = "black") + ylim(0, 200) +
  scale_y_continuous(breaks=c(0, 25, 50, 75, 100, 125)) +
  scale_x_discrete(labels=wrap_format(30)) +
  ggsave("2019 AUDPS figure.tiff", units="in", width=10, height=8, dpi=600)
```

Weather figures
```{r Import data, echo=TRUE}
data=read.csv("2019 Hoophouse_Weather.csv")
str(data)
data$hours=as.numeric(data$hours)
```

```{r Weather line graph, echo=FALSE}
ggplot(data, aes(x = hours)) +
  geom_line(aes(y=mTemp, color="Air Temperature"), size=1.5) +
  geom_line(aes(y=spd*3, color="Wind Speed"), size=1.5) +
  theme_bw() + theme(axis.title.y = element_text(size=13, color="black", face="bold"),
                     axis.title.x = element_text(size=15, color="black"), legend.position="none",
                     axis.text.x = element_text(size=10, color="black"),
                     axis.text.y = element_text(size=9, color="black"), 
                     panel.background = element_rect(fill="white"),
                     panel.grid.major=element_line(color="white"),
                     panel.grid.minor=element_line(color="white")) +
  scale_x_continuous(breaks=c(0,6,12,18,24,30,36,42,48)) +
  scale_y_continuous(sec.axis=sec_axis(~./3, name="Wind Speed (m/s)"), breaks=c(0, 10, 20, 30)) +
  scale_color_manual(values=c("lightcyan4", "firebrick4")) +
  labs(y="Air Temperature (°C)", x="Time following application (hours)", color="Parameter") +
  theme(legend.position=c(0.87,0.885)) +
  ggsave("2019 SB22 weather line.tiff", units="in", width=8, height=6, dpi=600)
```

```{r Wind rose p1, include=FALSE}
   # WindRose.R
require(ggplot2)
require(RColorBrewer)
require(scales)
plot.windrose <- function(data,
                          spd,
                          dir,
                          spdres = 2,
                          dirres = 22.5,
                          spdmin = 0,
                          spdmax = 6,
                          spdseq = NULL,
                          palette = "Blues", 
                          countmax = NA,
                          debug = 0){
  # Look to see what data was passed in to the function
  if (is.numeric(spd) & is.numeric(dir)){
    # assume that we've been given vectors of the speed and direction vectors
    data <- data.frame(spd = spd,
                       dir = dir)
    spd = "spd"
    dir = "dir"
  } else if (exists("data")){
    # Assume that we've been given a data frame, and the name of the speed 
    # and direction columns. This is the format we want for later use.    
  }  
  # Tidy up input data ----
  n.in <- NROW(data)
  dnu <- (is.na(data[[spd]]) | is.na(data[[dir]]))
  data[[spd]][dnu] <- NA
  data[[dir]][dnu] <- NA
  # figure out the wind speed bins ----
  if (missing(spdseq)){
    spdseq <- seq(spdmin,spdmax,spdres)
  } else {
    if (debug >0){
      cat("Using custom speed bins \n")
    }
  }
  # get some information about the number of bins, etc.
  n.spd.seq <- length(spdseq)
  n.colors.in.range <- n.spd.seq - 1
  # create the color map
  spd.colors <- colorRampPalette(brewer.pal(min(max(3,
                                                    n.colors.in.range),
                                                min(9,
                                                    n.colors.in.range)),                                               
                                            palette))(n.colors.in.range)
  if (max(data[[spd]],na.rm = TRUE) > spdmax){    
    spd.breaks <- c(spdseq,
                    max(data[[spd]],na.rm = TRUE))
    spd.labels <- c(paste(c(spdseq[1:n.spd.seq-1]),
                          '-',
                          c(spdseq[2:n.spd.seq])),
                    paste(spdmax,
                          "-",
                          max(data[[spd]],na.rm = TRUE)))
    spd.colors <- c(spd.colors, "grey50")
  } else{
    spd.breaks <- spdseq
    spd.labels <- paste(c(spdseq[1:n.spd.seq-1]),
                        '-',
                        c(spdseq[2:n.spd.seq]))    
  }
  data$spd.binned <- cut(x = data[[spd]],
                         breaks = spd.breaks,
                         labels = spd.labels,
                         ordered_result = TRUE)
  # figure out the wind direction bins
  dir.breaks <- c(-dirres/2,
                  seq(dirres/2, 360-dirres/2, by = dirres),
                  360+dirres/2)  
  dir.labels <- c(paste(360-dirres/2,"-",dirres/2),
                  paste(seq(dirres/2, 360-3*dirres/2, by = dirres),
                        "-",
                        seq(3*dirres/2, 360-dirres/2, by = dirres)),
                  paste(360-dirres/2,"-",dirres/2))
  # assign each wind direction to a bin
  dir.binned <- cut(data[[dir]],
                    breaks = dir.breaks,
                    ordered_result = TRUE)
  levels(dir.binned) <- dir.labels
  data$dir.binned <- dir.binned
  # Run debug if required ----
  if (debug>0){    
    cat(dir.breaks,"\n")
    cat(dir.labels,"\n")
    cat(levels(dir.binned),"\n")
  }  
  # create the plot ----
  p.windrose <- ggplot(data = data,
                       aes(x = dir.binned,
                           fill = spd.binned
                           ,y = (..count..)/sum(..count..)
                           ))+
    geom_bar() + 
    scale_x_discrete(drop = FALSE,
labels = c("N","","NE","", "E", "", "SE","", 
             "S","", "SW","", "W","","NW","")) +
    coord_polar(start = -((dirres/2)/360) * 2*pi) +
    scale_fill_manual(name = "Wind Speed (m/s)", 
                      values = spd.colors,
                      drop = FALSE) +
    theme(axis.title.x = element_blank(), strip.text.x = element_text(size = 12, colour = "black", face="bold", angle = 0), strip.background = element_rect(fill="grey95"),
          axis.text=element_text(size=14, color="black"), 
        axis.title=element_text(size=18,face="bold"), 
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "grey80"), legend.position="bottom", legend.direction = "horizontal", legend.box = "horizontal", legend.text = element_text(colour="black", size = 12), legend.title = element_text(colour="black", size=12, face="bold"),
  panel.grid.minor = element_blank())  + #facet_wrap(apprun~, ncol=2) +
    scale_y_continuous(labels = scales::percent_format(accuracy=1)) + 
    ylab("Frequency") 
  # adjust axes if required
  if (!is.na(countmax)){
    p.windrose <- p.windrose +
      ylim(c(0,countmax))
  }
  # print the plot
  print(p.windrose)  
  # return the handle to the wind rose
  return(p.windrose)
}
```

```{r Windrose Figure, echo=FALSE}
plot<-plot.windrose(data = data,
              spd = "spd",
              dir = "dir") 
plot +  #facet_wrap(~apprun) +  #labs(caption = "Oliveira et al. (2018) 96:1051-1063, the Plant Journal") +
    ggsave("2019 Wind Rose.png", units="in", width=6, height=5, dpi=600)
```