---
title: "Estudo no tunel baixo"
author: "Maxwel Coura Oliveira"
date: "9/2/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r include=FALSE}
library(tidyverse)
library(agricolae)
library(lme4)
library(lmerTest)
library(emmeans)
library(car)
library(cdlTools)
```


```{r}
dat14 <- read_csv("data_14dat.csv") %>% 
  pivot_longer(cols=6:20, names_to = "distance", values_to = "injury")

dat28 <- read_csv("data_28dat.csv") %>% 
  pivot_longer(cols=6:20, names_to = "distance", values_to = "injury")

data <- bind_rows(dat14, dat28) %>% 
  mutate(distance = as.double(distance)) %>% 
  mutate_if(is.character, factor) %>% 
  mutate(dat = factor(dat),
         unit = factor(unit))
```


```{r}
data %>% 
  filter(dat == "14" & treat == "DGA") %>% 
  ggplot(aes(x = distance, y = injury)) +
  geom_smooth() 
```



```{r}
Data = data %>%
  filter(unit=="1") 
#plot(Data$distance, Data$injury)
audps(Data$injury, Data$distance, type="absolute")
```






```{r}
data %>% 
  ggplot(aes(x=treat, y=auc, fill=treat)) + geom_bar(stat = "summary", show.legend = FALSE) +
  facet_grid(~ dat) + theme_bw() + coord_flip() +
  scale_color_brewer(palette = "Paired") +
  ggsave("Figure.png", height=6, width=12)
```




```{r}
dat <- data %>% 
  mutate(auc = (auc / 100) - 3) %>% 
  filter(treat != "untreated")

bartlett.test(auc ~ treat, data=dat)
leveneTest(auc ~ treat, data=dat)

dat <- dat %>%   
  mutate(tauc = sqrt(auc))

plot(density(dat$auc))
qqnorm(dat$auc); qqline(dat$auc, col=2)
#pearson.test(dat$auc)
#leveneTest(auc ~ Trtdes, data=Data2)

#ggdensity(dat$auc, Main = "Density Plot", xlab = "AUDPS")
```


```{r}
#model using sqrt transformation

dat14 <- dat %>%  filter(dat == "14")

model = lmer(auc ~ treat + (1|rep), data=dat14)

anova(model, test.statistic = "F")
```

```{r}
emmip(model, ~ treat, type="response") + coord_flip()
```


```{r}
lsmeans <- emmeans(model, ~ treat, adjust="none", contr="pairwise")
lsmeans
```


```{r}
plot(lsmeans, ~ herbicide, comparisons=TRUE, alpha=0.05, adjust="none")
```


```{r}
nd <- as.data.frame(lsmeans$emmeans)
ggplot(nd, aes(x=reorder(treat,emmean), y=emmean, color=treat)) + 
geom_point(size=4) + 
#scale_color_manual(values=c("red", "blue", "green", "orange", "purple")) +
theme_bw() + labs(y="Area Under Injury over Distance Stairs (AUIDS)", x="Herbicides") +
geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size=1.5) + 
theme(axis.title = element_text(size=16),
axis.text = element_text(size=15),
legend.position = "none") +
coord_flip() + 
  ggsave("injury_auc_14.png", units="in", width=10, height=6, dpi=600)
```


```{r warning=FALSE, message=FALSE}
library(multcomp)
cld <-cld(lsmeans$emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)

cld
```





```{r}
#model using sqrt transformation

dat28 <- dat %>%  filter(dat == "28")

model=lmer(auc ~ treat + (1|rep), data=dat28)
anova(model, test.statistic = "F")
```

```{r}
emmip(model, ~ treat, type="response") + coord_flip()
```


```{r}
lsmeans <- emmeans(model, ~ treat, adjust="none", contr="pairwise")
lsmeans
```


```{r}
plot(lsmeans, ~ herbicide, comparisons=TRUE, alpha=0.05, adjust="none")
```


```{r}
nd <- as.data.frame(lsmeans$emmeans)
ggplot(nd, aes(x=reorder(treat,emmean), y=emmean, color=treat)) + 
geom_point(size=4) + 
#scale_color_manual(values=c("red", "blue", "green", "orange", "purple")) +
theme_bw() + labs(y="Area Under Injury over Distance Stairs (AUIDS)", x="Herbicides") +
geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size=1.5) + 
theme(axis.title = element_text(size=16),
axis.text = element_text(size=15),
legend.position = "none") +
coord_flip() + 
  ggsave("injury_auc_28.png", units="in", width=10, height=6, dpi=600)
```


```{r warning=FALSE, message=FALSE}
cld <-CLD(lsmeans$emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)

cld
```
